# Book settings
title: Remote Sensing with Google Earth Engine
author: Cale Kochenour
# logo: logo.png

# Execution settings
execute:
  execute_notebooks         : off

# HTML-specific settings
html:
  home_page_in_navbar       : false

# Launch button settings
launch_buttons:
  notebook_interface        : classic
  binderhub_url             : https://mybinder.org
  colab_url                 : https://colab.research.google.com

repository:
  url                       : https://github.com/calekochenour/remote-sensing-textbook
  path_to_book              : content
  branch                    : master
